package nyp_donem_odevi;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author bunuox
 */
public class GirisEkrani extends javax.swing.JFrame {

    /**
     * Creates new form GirisEkrani
     */
    public GirisEkrani() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void girisKontrol(Kullanici k){
        k.girisYapildi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        musteri_tc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        musteri_sifre = new javax.swing.JTextField();
        musteri_giris_onay_button = new javax.swing.JButton();
        kayit_dialog = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        dialog_telefon = new javax.swing.JTextField();
        dialog_ad = new javax.swing.JTextField();
        dialog_soyad = new javax.swing.JTextField();
        dialog_sifre = new javax.swing.JPasswordField();
        dialog_sifre_tekrar = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        dialog_cinsiyet = new javax.swing.JComboBox<>();
        dialog_tc = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        ResimPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        personel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        kullanici = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        kullaniciGiris = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        kullanici_tc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        kullanici_giris_button = new javax.swing.JButton();
        kullanici_sifre = new javax.swing.JPasswordField();
        personelGiris = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        personel_id = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        personel_giris_button = new javax.swing.JButton();
        personel_sifre = new javax.swing.JPasswordField();

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(236, 85, 85));
        jLabel3.setText("T.C. Kimlik Numarası:");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 180, 30));

        musteri_tc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteri_tcActionPerformed(evt);
            }
        });
        jPanel7.add(musteri_tc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 210, -1));

        jLabel4.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(237, 59, 68));
        jLabel4.setText("Şifre:");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));
        jPanel7.add(musteri_sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 210, -1));

        musteri_giris_onay_button.setText("Giriş");
        jPanel7.add(musteri_giris_onay_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 60, -1));

        jLabel10.setFont(new java.awt.Font("Source Sans Pro", 0, 18)); // NOI18N
        jLabel10.setText("Ad:");

        jLabel11.setFont(new java.awt.Font("Source Sans Pro", 0, 18)); // NOI18N
        jLabel11.setText("Soyad:");

        jLabel12.setFont(new java.awt.Font("Source Sans Pro", 0, 18)); // NOI18N
        jLabel12.setText("Telefon:");

        jLabel13.setFont(new java.awt.Font("Source Sans Pro", 0, 18)); // NOI18N
        jLabel13.setText("T.C:");

        jLabel14.setFont(new java.awt.Font("Source Sans Pro", 0, 18)); // NOI18N
        jLabel14.setText("Cinsiyet:");

        jLabel15.setFont(new java.awt.Font("Source Sans Pro", 0, 18)); // NOI18N
        jLabel15.setText("Şifre:");

        jLabel16.setFont(new java.awt.Font("Source Sans Pro", 0, 18)); // NOI18N
        jLabel16.setText("Şifre (Tekrar):");

        dialog_telefon.setFont(new java.awt.Font("Source Sans Pro", 0, 18)); // NOI18N

        dialog_ad.setFont(new java.awt.Font("Source Sans Pro", 0, 18)); // NOI18N

        dialog_soyad.setFont(new java.awt.Font("Source Sans Pro", 0, 18)); // NOI18N

        dialog_sifre.setFont(new java.awt.Font("Source Sans Pro", 0, 18)); // NOI18N

        dialog_sifre_tekrar.setFont(new java.awt.Font("Source Sans Pro", 0, 18)); // NOI18N

        jButton2.setText("Onayla");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        dialog_cinsiyet.setFont(new java.awt.Font("Source Sans Pro", 0, 18)); // NOI18N
        dialog_cinsiyet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "E", "K" }));

        try {
            dialog_tc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout kayit_dialogLayout = new javax.swing.GroupLayout(kayit_dialog.getContentPane());
        kayit_dialog.getContentPane().setLayout(kayit_dialogLayout);
        kayit_dialogLayout.setHorizontalGroup(
            kayit_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kayit_dialogLayout.createSequentialGroup()
                .addGroup(kayit_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kayit_dialogLayout.createSequentialGroup()
                        .addGroup(kayit_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kayit_dialogLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(kayit_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addGroup(kayit_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGroup(kayit_dialogLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel16)))
                        .addGap(66, 66, 66)
                        .addGroup(kayit_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dialog_telefon)
                            .addComponent(dialog_soyad, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(dialog_ad, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(dialog_sifre)
                            .addComponent(dialog_sifre_tekrar)
                            .addComponent(dialog_cinsiyet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dialog_tc))
                        .addGap(0, 131, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kayit_dialogLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        kayit_dialogLayout.setVerticalGroup(
            kayit_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kayit_dialogLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(kayit_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(dialog_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(kayit_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(dialog_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(kayit_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(dialog_telefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(kayit_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kayit_dialogLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(kayit_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(dialog_tc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(kayit_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(dialog_cinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addContainerGap())
                    .addGroup(kayit_dialogLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(dialog_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kayit_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dialog_sifre_tekrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addContainerGap(73, Short.MAX_VALUE))))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.blue);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(31, 31, 31));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ResimPanel.setBackground(new java.awt.Color(255, 4, 4));
        ResimPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(1, 1, 1));
        jButton1.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(254, 254, 254));
        jButton1.setText("Kayıt Ol");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nyp_donem_odevi/giris_pht.png"))); // NOI18N
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, -1));

        ResimPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, -1));

        jPanel4.add(ResimPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 580));

        jPanel1.setBackground(new java.awt.Color(31, 31, 31));

        jPanel2.setBackground(new java.awt.Color(148, 73, 129));
        jPanel2.setForeground(new java.awt.Color(126, 43, 151));

        personel.setBackground(new java.awt.Color(62, 62, 62));
        personel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GirisEkrani.this.mouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(248, 241, 241));
        jLabel2.setText("PERSONEL");

        javax.swing.GroupLayout personelLayout = new javax.swing.GroupLayout(personel);
        personel.setLayout(personelLayout);
        personelLayout.setHorizontalGroup(
            personelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        personelLayout.setVerticalGroup(
            personelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kullanici.setBackground(new java.awt.Color(62, 62, 62));
        kullanici.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        kullanici.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GirisEkrani.this.mouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 250, 250));
        jLabel1.setText("KULLANICI");

        javax.swing.GroupLayout kullaniciLayout = new javax.swing.GroupLayout(kullanici);
        kullanici.setLayout(kullaniciLayout);
        kullaniciLayout.setHorizontalGroup(
            kullaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kullaniciLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        kullaniciLayout.setVerticalGroup(
            kullaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kullaniciLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kullanici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(personel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(personel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kullanici, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 380, -1));

        jPanel6.setBackground(new java.awt.Color(31, 31, 31));
        jPanel6.setLayout(new java.awt.CardLayout());

        kullaniciGiris.setFont(new java.awt.Font("Source Sans Pro", 1, 24)); // NOI18N
        kullaniciGiris.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Kullanıcı T.C.");

        kullanici_tc.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Şifre: ");

        kullanici_giris_button.setBackground(new java.awt.Color(1, 1, 1));
        kullanici_giris_button.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        kullanici_giris_button.setForeground(new java.awt.Color(255, 255, 255));
        kullanici_giris_button.setText("Giriş");
        kullanici_giris_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullanici_giris_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kullaniciGirisLayout = new javax.swing.GroupLayout(kullaniciGiris);
        kullaniciGiris.setLayout(kullaniciGirisLayout);
        kullaniciGirisLayout.setHorizontalGroup(
            kullaniciGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kullaniciGirisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kullaniciGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kullanici_giris_button, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kullaniciGirisLayout.createSequentialGroup()
                        .addGroup(kullaniciGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kullaniciGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kullanici_tc, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(kullanici_sifre))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        kullaniciGirisLayout.setVerticalGroup(
            kullaniciGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kullaniciGirisLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(kullaniciGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(kullanici_tc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106)
                .addGroup(kullaniciGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(kullanici_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(kullanici_giris_button)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jPanel6.add(kullaniciGiris, "card2");

        personelGiris.setBackground(new java.awt.Color(31, 31, 31));

        jPanel10.setBackground(new java.awt.Color(31, 31, 31));
        jPanel10.setFont(new java.awt.Font("Source Sans Pro", 1, 24)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Personel ID");

        personel_id.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Şifre: ");

        personel_giris_button.setBackground(new java.awt.Color(1, 1, 1));
        personel_giris_button.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        personel_giris_button.setForeground(new java.awt.Color(255, 255, 255));
        personel_giris_button.setText("Giriş");
        personel_giris_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personel_giris_buttonActionPerformed(evt);
            }
        });

        personel_sifre.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(personel_giris_button, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(125, 125, 125))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)))
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(personel_id, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(personel_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personel_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(105, 105, 105)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(personel_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(personel_giris_button)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout personelGirisLayout = new javax.swing.GroupLayout(personelGiris);
        personelGiris.setLayout(personelGirisLayout);
        personelGirisLayout.setHorizontalGroup(
            personelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
            .addGroup(personelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(personelGirisLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        personelGirisLayout.setVerticalGroup(
            personelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
            .addGroup(personelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(personelGirisLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel6.add(personelGiris, "card3");

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 370, 420));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void musteri_tcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteri_tcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_musteri_tcActionPerformed

    private void mouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClicked
        // TODO add your handling code here:

        if (evt.getSource() == personel) {
            personelGiris.setVisible(true);
            kullaniciGiris.setVisible(false);
        }

        if (evt.getSource() == kullanici) {
            personelGiris.setVisible(false);
            kullaniciGiris.setVisible(true);
        }
    }//GEN-LAST:event_mouseClicked

    private void personel_giris_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personel_giris_buttonActionPerformed
        // TODO add your handling code here:
        Scanner reader;
        int kontrol = 0;
        try {
            reader = new Scanner(new BufferedReader(new FileReader("banka_personeli.txt")));
            while (reader.hasNextLine()) {
                String s = reader.nextLine();
                String[] bilgiler = s.split(",");

                if (bilgiler[0].equals(personel_id.getText()) && bilgiler[4].equals(personel_sifre.getText()) && bilgiler[10].equals("1") && bilgiler[1].equals("PERSONEL")) {
                    kontrol = 1;
                    BankaCalisan b = new BankaCalisan(Integer.parseInt(bilgiler[0]));
                    PersonelEkran p = new PersonelEkran(b);
                    girisKontrol(b);
                    p.setVisible(true);
                    this.setVisible(false);
                }

                if (bilgiler[0].equals(personel_id.getText()) && bilgiler[4].equals(personel_sifre.getText()) && bilgiler[10].equals("1") && bilgiler[1].equals("YONETICI")) {
                    kontrol = 1;
                    BankaYonetici b = new BankaYonetici(Integer.parseInt(bilgiler[0]));
                    bankaYoneticiEkran p = new bankaYoneticiEkran(b);
                    p.setVisible(true);
                    girisKontrol(b);
                    this.setVisible(false);
                }

            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GirisEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(kontrol == 0){
            JOptionPane.showMessageDialog(null, "Girdiğiniz bilgilerde personel bulunmamakta!");
        }
    }//GEN-LAST:event_personel_giris_buttonActionPerformed

    private void kullanici_giris_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullanici_giris_buttonActionPerformed
        // TODO add your handling code here:
        Scanner reader;
        int kontrol = 0;
        try {
            reader = new Scanner(new BufferedReader(new FileReader("musteri.txt")));
            while (reader.hasNextLine()) {
                String s = reader.nextLine();
                String[] bilgiler = s.split(",");
                if (bilgiler[5].equals(kullanici_tc.getText()) && bilgiler[3].equals(kullanici_sifre.getText()) && bilgiler[7].equals("1")) {
                    kontrol = 1;
                    Musteri m = new Musteri(Integer.parseInt(bilgiler[0]));
                    musteriEkran d = new musteriEkran(m);
                    girisKontrol(m);
                    d.setVisible(true);
                    this.setVisible(false);
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GirisEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(kontrol == 0){
            JOptionPane.showMessageDialog(null, "Girdiğiniz bilgilerde müşteri bulunmamakta!");
        }
    }//GEN-LAST:event_kullanici_giris_buttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        kayit_dialog.setLocationRelativeTo(null);
        kayit_dialog.pack();
        kayit_dialog.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            double tc = Double.parseDouble(dialog_tc.getText());

            if (dialog_sifre.getText().equals(dialog_sifre_tekrar.getText())) {

                String ad = dialog_ad.getText();
                String soyad = dialog_soyad.getText();
                String telefon = dialog_telefon.getText();
                String cinsiyet = dialog_cinsiyet.getSelectedItem().toString();
                String sifre = dialog_sifre.getText();

                Musteri m;
                try {
                    m = new Musteri(ad, soyad, sifre, telefon,dialog_tc.getText(), cinsiyet);
                    m.musteriKaydet();
                } catch (IOException ex) {
                    Logger.getLogger(GirisEkrani.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Girdiğiniz şifreler uyuşmuyor!");
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Lütfen geçerli bir tc kimlik giriniz!");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GirisEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ResimPanel;
    private javax.swing.JTextField dialog_ad;
    private javax.swing.JComboBox<String> dialog_cinsiyet;
    private javax.swing.JPasswordField dialog_sifre;
    private javax.swing.JPasswordField dialog_sifre_tekrar;
    private javax.swing.JTextField dialog_soyad;
    private javax.swing.JFormattedTextField dialog_tc;
    private javax.swing.JTextField dialog_telefon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JDialog kayit_dialog;
    private javax.swing.JPanel kullanici;
    private javax.swing.JPanel kullaniciGiris;
    private javax.swing.JButton kullanici_giris_button;
    private javax.swing.JPasswordField kullanici_sifre;
    private javax.swing.JTextField kullanici_tc;
    private javax.swing.JButton musteri_giris_onay_button;
    private javax.swing.JTextField musteri_sifre;
    private javax.swing.JTextField musteri_tc;
    private javax.swing.JPanel personel;
    private javax.swing.JPanel personelGiris;
    private javax.swing.JButton personel_giris_button;
    private javax.swing.JTextField personel_id;
    private javax.swing.JPasswordField personel_sifre;
    // End of variables declaration//GEN-END:variables
}
