package nyp_donem_odevi;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author bunuox
 */
public class PersonelEkran extends javax.swing.JFrame {

    /**
     * Creates new form PersonelEkran
     */
    BankaCalisan b;

    public PersonelEkran() {
        initComponents();
    }

    public PersonelEkran(BankaCalisan b) {
        this.b = b;
        initComponents();
        personel_adi.setText("Hoşgeldiniz: " + this.b.name);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        musteri_guncelle = new javax.swing.JDialog();
        dialog_ad = new javax.swing.JTextField();
        dialog_soyad = new javax.swing.JTextField();
        dialog_telefon = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        dialog_guncelle_button = new javax.swing.JButton();
        dialog_sifre = new javax.swing.JPasswordField();
        musteri_guncelle_sil_button = new javax.swing.JButton();
        sifre_degistir = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        dialog_yeni_sifre = new javax.swing.JPasswordField();
        dialog_mevcut_sifre = new javax.swing.JPasswordField();
        dialog_sifre_onay_button = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        buton_panel_1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buton_panel_2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        buton_panel_3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        buton_panel_4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        buton_panel_5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        buton_panel_6 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        buton_panel_7 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        personel_adi = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        ana_alan = new javax.swing.JPanel();
        p1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        p1_musteri_table = new javax.swing.JTable();
        bilg_guncelle_button = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        p2_kredi_table = new javax.swing.JTable();
        p2_kredi_reddet_button = new javax.swing.JButton();
        p2_kredi_onayla_button = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        p3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        p3_ad = new javax.swing.JTextField();
        p3_tc = new javax.swing.JTextField();
        p3_soyad = new javax.swing.JTextField();
        p3_sifre = new javax.swing.JTextField();
        p3_telefon = new javax.swing.JTextField();
        p3_ekle_button = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        p3_cinsiyet = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        p4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        p4_islem_table = new javax.swing.JTable();
        p5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        p5_calisan_id = new javax.swing.JTextField();
        p5_calisan_ad = new javax.swing.JTextField();
        p5_calisan_telefon = new javax.swing.JTextField();
        p5_calisan_tc = new javax.swing.JTextField();
        p5_calisan_sube = new javax.swing.JTextField();
        p5_calisan_soyad = new javax.swing.JTextField();
        p5_calisan_unvan = new javax.swing.JTextField();
        p5_calisan_maas = new javax.swing.JTextField();
        p5_sifre_degistir_button = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        p6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        p6_kredi_limit_table = new javax.swing.JTable();
        p6_red_button = new javax.swing.JButton();
        p6_onay_button = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        p7 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        p7_kredi_table = new javax.swing.JTable();
        p7_onayla_button = new javax.swing.JButton();
        p7_red_button = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();

        jLabel20.setText("*Ad: ");

        jLabel22.setText("*Soyad: ");

        jLabel23.setText("*Şifre:");

        jLabel24.setText("*Telefon: ");

        dialog_guncelle_button.setText("Güncelle");
        dialog_guncelle_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialog_guncelle_buttonActionPerformed(evt);
            }
        });

        dialog_sifre.setText("jPasswordField1");

        musteri_guncelle_sil_button.setText("Sil");
        musteri_guncelle_sil_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteri_guncelle_sil_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout musteri_guncelleLayout = new javax.swing.GroupLayout(musteri_guncelle.getContentPane());
        musteri_guncelle.getContentPane().setLayout(musteri_guncelleLayout);
        musteri_guncelleLayout.setHorizontalGroup(
            musteri_guncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musteri_guncelleLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(musteri_guncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24))
                .addGap(89, 89, 89)
                .addGroup(musteri_guncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dialog_ad, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(dialog_soyad, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(dialog_telefon, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(dialog_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, musteri_guncelleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(musteri_guncelle_sil_button)
                .addGap(26, 26, 26)
                .addComponent(dialog_guncelle_button)
                .addGap(22, 22, 22))
        );
        musteri_guncelleLayout.setVerticalGroup(
            musteri_guncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musteri_guncelleLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(musteri_guncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(dialog_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(musteri_guncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(dialog_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(musteri_guncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(dialog_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(musteri_guncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(dialog_telefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(musteri_guncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dialog_guncelle_button)
                    .addComponent(musteri_guncelle_sil_button))
                .addContainerGap())
        );

        jLabel21.setText("Mevcut Şifre: ");

        jLabel25.setText("Yeni Şifre:");

        dialog_sifre_onay_button.setText("Onayla");
        dialog_sifre_onay_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialog_sifre_onay_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sifre_degistirLayout = new javax.swing.GroupLayout(sifre_degistir.getContentPane());
        sifre_degistir.getContentPane().setLayout(sifre_degistirLayout);
        sifre_degistirLayout.setHorizontalGroup(
            sifre_degistirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sifre_degistirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sifre_degistirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(sifre_degistirLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(71, 71, 71)
                        .addComponent(dialog_yeni_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sifre_degistirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dialog_sifre_onay_button)
                .addContainerGap())
            .addGroup(sifre_degistirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sifre_degistirLayout.createSequentialGroup()
                    .addContainerGap(160, Short.MAX_VALUE)
                    .addComponent(dialog_mevcut_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(91, 91, 91)))
        );
        sifre_degistirLayout.setVerticalGroup(
            sifre_degistirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sifre_degistirLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel21)
                .addGap(86, 86, 86)
                .addGroup(sifre_degistirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(dialog_yeni_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(dialog_sifre_onay_button)
                .addContainerGap())
            .addGroup(sifre_degistirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(sifre_degistirLayout.createSequentialGroup()
                    .addGap(68, 68, 68)
                    .addComponent(dialog_mevcut_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(201, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(33, 105, 238));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(253, 105, 26));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buton_panel_1.setBackground(new java.awt.Color(208, 56, 159));
        buton_panel_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PersonelEkran.this.mouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Müşterileri Göster");

        javax.swing.GroupLayout buton_panel_1Layout = new javax.swing.GroupLayout(buton_panel_1);
        buton_panel_1.setLayout(buton_panel_1Layout);
        buton_panel_1Layout.setHorizontalGroup(
            buton_panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        buton_panel_1Layout.setVerticalGroup(
            buton_panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buton_panel_1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel5.add(buton_panel_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 230, -1));

        buton_panel_2.setBackground(new java.awt.Color(208, 56, 159));
        buton_panel_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PersonelEkran.this.mouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Kredi Bekleyen İşlemler");

        javax.swing.GroupLayout buton_panel_2Layout = new javax.swing.GroupLayout(buton_panel_2);
        buton_panel_2.setLayout(buton_panel_2Layout);
        buton_panel_2Layout.setHorizontalGroup(
            buton_panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buton_panel_2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 45, Short.MAX_VALUE))
        );
        buton_panel_2Layout.setVerticalGroup(
            buton_panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buton_panel_2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel5.add(buton_panel_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 230, -1));

        buton_panel_3.setBackground(new java.awt.Color(208, 56, 159));
        buton_panel_3.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        buton_panel_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PersonelEkran.this.mouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Müşteri Ekle");

        javax.swing.GroupLayout buton_panel_3Layout = new javax.swing.GroupLayout(buton_panel_3);
        buton_panel_3.setLayout(buton_panel_3Layout);
        buton_panel_3Layout.setHorizontalGroup(
            buton_panel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buton_panel_3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 132, Short.MAX_VALUE))
        );
        buton_panel_3Layout.setVerticalGroup(
            buton_panel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buton_panel_3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jPanel5.add(buton_panel_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 195, 230, -1));

        buton_panel_4.setBackground(new java.awt.Color(208, 56, 159));
        buton_panel_4.setPreferredSize(new java.awt.Dimension(220, 51));
        buton_panel_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PersonelEkran.this.mouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Müşteri İşlem Geçmişi");

        javax.swing.GroupLayout buton_panel_4Layout = new javax.swing.GroupLayout(buton_panel_4);
        buton_panel_4.setLayout(buton_panel_4Layout);
        buton_panel_4Layout.setHorizontalGroup(
            buton_panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4)
        );
        buton_panel_4Layout.setVerticalGroup(
            buton_panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buton_panel_4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jPanel5.add(buton_panel_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 285, 230, -1));

        buton_panel_5.setBackground(new java.awt.Color(208, 56, 159));
        buton_panel_5.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        buton_panel_5.setPreferredSize(new java.awt.Dimension(220, 51));
        buton_panel_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PersonelEkran.this.mouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Bilgilerimi Göster");

        javax.swing.GroupLayout buton_panel_5Layout = new javax.swing.GroupLayout(buton_panel_5);
        buton_panel_5.setLayout(buton_panel_5Layout);
        buton_panel_5Layout.setHorizontalGroup(
            buton_panel_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buton_panel_5Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 92, Short.MAX_VALUE))
        );
        buton_panel_5Layout.setVerticalGroup(
            buton_panel_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buton_panel_5Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jPanel5.add(buton_panel_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 230, -1));

        buton_panel_6.setBackground(new java.awt.Color(208, 56, 159));
        buton_panel_6.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        buton_panel_6.setPreferredSize(new java.awt.Dimension(220, 51));
        buton_panel_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PersonelEkran.this.mouseClicked(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(254, 254, 254));
        jLabel32.setText("Limit Bekleyen İşlemler");

        javax.swing.GroupLayout buton_panel_6Layout = new javax.swing.GroupLayout(buton_panel_6);
        buton_panel_6.setLayout(buton_panel_6Layout);
        buton_panel_6Layout.setHorizontalGroup(
            buton_panel_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buton_panel_6Layout.createSequentialGroup()
                .addComponent(jLabel32)
                .addGap(0, 46, Short.MAX_VALUE))
        );
        buton_panel_6Layout.setVerticalGroup(
            buton_panel_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buton_panel_6Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel32)
                .addContainerGap())
        );

        jPanel5.add(buton_panel_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 230, -1));

        buton_panel_7.setBackground(new java.awt.Color(208, 56, 159));
        buton_panel_7.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        buton_panel_7.setPreferredSize(new java.awt.Dimension(220, 51));
        buton_panel_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PersonelEkran.this.mouseClicked(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Source Sans Pro", 1, 17)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(254, 254, 254));
        jLabel34.setText("Kredi Kartı Bekleyen İşlemler");

        javax.swing.GroupLayout buton_panel_7Layout = new javax.swing.GroupLayout(buton_panel_7);
        buton_panel_7.setLayout(buton_panel_7Layout);
        buton_panel_7Layout.setHorizontalGroup(
            buton_panel_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buton_panel_7Layout.createSequentialGroup()
                .addComponent(jLabel34)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        buton_panel_7Layout.setVerticalGroup(
            buton_panel_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buton_panel_7Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel34)
                .addContainerGap())
        );

        jPanel5.add(buton_panel_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 230, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nyp_donem_odevi/sol.png"))); // NOI18N
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 710));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 710));

        jPanel1.setBackground(new java.awt.Color(24, 101, 241));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        personel_adi.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        personel_adi.setText("ddddddddddddddddddddddddddddddddddd");
        jPanel1.add(personel_adi, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, -1, 30));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nyp_donem_odevi/50x50.png"))); // NOI18N
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nyp_donem_odevi/ust.png"))); // NOI18N
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, -1));

        ana_alan.setLayout(new java.awt.CardLayout());

        p1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p1_musteri_table.setFont(new java.awt.Font("Source Sans Pro", 0, 16)); // NOI18N
        p1_musteri_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Musteri ID", "İsim", "Soyisim", "Numara", "TC", "Cinsiyet"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        p1_musteri_table.setFocusable(false);
        p1_musteri_table.setIntercellSpacing(new java.awt.Dimension(0, 0));
        p1_musteri_table.setRowHeight(25);
        p1_musteri_table.setSelectionBackground(new java.awt.Color(232, 57, 95));
        p1_musteri_table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        p1_musteri_table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        p1_musteri_table.setShowVerticalLines(false);
        p1_musteri_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(p1_musteri_table);

        p1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 1100, 354));

        bilg_guncelle_button.setText("Bilgi Güncelle");
        bilg_guncelle_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilg_guncelle_buttonActionPerformed(evt);
            }
        });
        p1.add(bilg_guncelle_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 620, -1, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nyp_donem_odevi/sag.png"))); // NOI18N
        p1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, -1));

        ana_alan.add(p1, "card2");

        p2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p2_kredi_table.setFont(new java.awt.Font("Source Sans Pro", 0, 16)); // NOI18N
        p2_kredi_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kredi ID", "Müşteri ID", "Kredi Tür", "Kredi Vade", "Kredi Tutarı", "Ödenecek Tutar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        p2_kredi_table.setFocusable(false);
        p2_kredi_table.setIntercellSpacing(new java.awt.Dimension(0, 0));
        p2_kredi_table.setRowHeight(25);
        p2_kredi_table.setSelectionBackground(new java.awt.Color(232, 57, 95));
        p2_kredi_table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        p2_kredi_table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        p2_kredi_table.setShowVerticalLines(false);
        p2_kredi_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(p2_kredi_table);
        if (p2_kredi_table.getColumnModel().getColumnCount() > 0) {
            p2_kredi_table.getColumnModel().getColumn(4).setHeaderValue("Kredi Tutarı");
            p2_kredi_table.getColumnModel().getColumn(5).setHeaderValue("Ödenecek Tutar");
        }

        p2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 1100, 409));

        p2_kredi_reddet_button.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        p2_kredi_reddet_button.setText("Kredi Reddet");
        p2_kredi_reddet_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2_kredi_reddet_buttonActionPerformed(evt);
            }
        });
        p2.add(p2_kredi_reddet_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 610, -1, -1));

        p2_kredi_onayla_button.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        p2_kredi_onayla_button.setText("Kredi Onayla");
        p2_kredi_onayla_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2_kredi_onayla_buttonActionPerformed(evt);
            }
        });
        p2.add(p2_kredi_onayla_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 610, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nyp_donem_odevi/sag.png"))); // NOI18N
        jLabel29.setMaximumSize(new java.awt.Dimension(1212, 760));
        jLabel29.setMinimumSize(new java.awt.Dimension(1212, 760));
        jLabel29.setPreferredSize(new java.awt.Dimension(1212, 760));
        p2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        ana_alan.add(p2, "card3");

        p3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        jLabel6.setText("*Ad: ");
        p3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 85, -1));

        jLabel7.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        jLabel7.setText("*Soyad: ");
        p3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 85, -1));

        jLabel8.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        jLabel8.setText("*Şifre:");
        p3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 85, -1));

        jLabel9.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        jLabel9.setText("*Telefon: ");
        p3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, -1, -1));

        jLabel10.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        jLabel10.setText("*TC: ");
        p3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, -1, -1));

        p3_ad.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        p3_ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3_adActionPerformed(evt);
            }
        });
        p3.add(p3_ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 120, -1));

        p3_tc.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        p3.add(p3_tc, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 120, -1));

        p3_soyad.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        p3.add(p3_soyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 120, -1));

        p3_sifre.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        p3.add(p3_sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 120, -1));

        p3_telefon.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        p3.add(p3_telefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 120, -1));

        p3_ekle_button.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        p3_ekle_button.setText("Ekle");
        p3_ekle_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3_ekle_buttonActionPerformed(evt);
            }
        });
        p3.add(p3_ekle_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 610, 119, -1));

        jLabel11.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        jLabel11.setText("Cinsiyet");
        p3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, -1, -1));

        p3_cinsiyet.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        p3_cinsiyet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "E", "K" }));
        p3.add(p3_cinsiyet, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, -1, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nyp_donem_odevi/sag.png"))); // NOI18N
        p3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, -1));

        ana_alan.add(p3, "card4");

        p4_islem_table.setFont(new java.awt.Font("Source Sans Pro", 0, 16)); // NOI18N
        p4_islem_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Müşteri ID", "İşlem Tutarı", "İşlem Açıklaması", "İşlem Yöntemi", "İşlem Tarihi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        p4_islem_table.setFocusable(false);
        p4_islem_table.setIntercellSpacing(new java.awt.Dimension(0, 0));
        p4_islem_table.setRowHeight(25);
        p4_islem_table.setSelectionBackground(new java.awt.Color(232, 57, 95));
        p4_islem_table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        p4_islem_table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        p4_islem_table.setShowVerticalLines(false);
        p4_islem_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(p4_islem_table);

        javax.swing.GroupLayout p4Layout = new javax.swing.GroupLayout(p4);
        p4.setLayout(p4Layout);
        p4Layout.setHorizontalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p4Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        p4Layout.setVerticalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );

        ana_alan.add(p4, "card5");

        p5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        jLabel12.setText("ID: ");
        p5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        jLabel13.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        jLabel13.setText("Ad: ");
        p5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        jLabel14.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        jLabel14.setText("Soyad: ");
        p5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        jLabel15.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        jLabel15.setText("Telefon: ");
        p5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        jLabel16.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        jLabel16.setText("T.C: ");
        p5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, -1, -1));

        jLabel17.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        jLabel17.setText("Ünvan: ");
        jLabel17.setFocusTraversalPolicyProvider(true);
        p5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, -1, -1));

        jLabel18.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        jLabel18.setText("Maaş: ");
        p5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, -1, -1));

        jLabel19.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        jLabel19.setText("Şube: ");
        p5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 570, -1, -1));

        p5_calisan_id.setEditable(false);
        p5_calisan_id.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        p5.add(p5_calisan_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 148, -1));

        p5_calisan_ad.setEditable(false);
        p5_calisan_ad.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        p5.add(p5_calisan_ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 148, -1));

        p5_calisan_telefon.setEditable(false);
        p5_calisan_telefon.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        p5.add(p5_calisan_telefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 148, -1));

        p5_calisan_tc.setEditable(false);
        p5_calisan_tc.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        p5.add(p5_calisan_tc, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 148, -1));

        p5_calisan_sube.setEditable(false);
        p5_calisan_sube.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        p5.add(p5_calisan_sube, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 560, 148, -1));

        p5_calisan_soyad.setEditable(false);
        p5_calisan_soyad.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        p5.add(p5_calisan_soyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 148, -1));

        p5_calisan_unvan.setEditable(false);
        p5_calisan_unvan.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        p5.add(p5_calisan_unvan, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, 148, -1));

        p5_calisan_maas.setEditable(false);
        p5_calisan_maas.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        p5.add(p5_calisan_maas, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, 148, -1));

        p5_sifre_degistir_button.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        p5_sifre_degistir_button.setText("Şifre Değiştir");
        p5_sifre_degistir_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p5_sifre_degistir_buttonActionPerformed(evt);
            }
        });
        p5.add(p5_sifre_degistir_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 610, -1, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nyp_donem_odevi/sag.png"))); // NOI18N
        p5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, -1));

        ana_alan.add(p5, "card6");

        p6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p6_kredi_limit_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kredi Kartı ID", "Mevcut Limit", "İstenen Limit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(p6_kredi_limit_table);

        p6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 1100, -1));

        p6_red_button.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        p6_red_button.setText("Reddet");
        p6_red_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p6_red_buttonActionPerformed(evt);
            }
        });
        p6.add(p6_red_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 620, -1, -1));

        p6_onay_button.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        p6_onay_button.setText("Onayla");
        p6_onay_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p6_onay_buttonActionPerformed(evt);
            }
        });
        p6.add(p6_onay_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 620, -1, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nyp_donem_odevi/sag.png"))); // NOI18N
        p6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, -1));

        ana_alan.add(p6, "card7");

        p7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p7_kredi_table.setFont(new java.awt.Font("Source Sans Pro", 0, 16)); // NOI18N
        p7_kredi_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Müşteri ID", "Kredi Kartı ID", "Kredi Kartı No", "Limit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        p7_kredi_table.setFocusable(false);
        p7_kredi_table.setIntercellSpacing(new java.awt.Dimension(0, 0));
        p7_kredi_table.setRowHeight(25);
        p7_kredi_table.setSelectionBackground(new java.awt.Color(252, 57, 95));
        p7_kredi_table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        p7_kredi_table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        p7_kredi_table.setShowVerticalLines(false);
        jScrollPane10.setViewportView(p7_kredi_table);

        p7.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 1100, 388));

        p7_onayla_button.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        p7_onayla_button.setText("Onayla");
        p7_onayla_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p7_onayla_buttonActionPerformed(evt);
            }
        });
        p7.add(p7_onayla_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 620, -1, -1));

        p7_red_button.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        p7_red_button.setText("Reddet");
        p7_red_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p7_red_buttonActionPerformed(evt);
            }
        });
        p7.add(p7_red_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 620, -1, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nyp_donem_odevi/sag.png"))); // NOI18N
        p7.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, -1));

        ana_alan.add(p7, "card8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ana_alan, javax.swing.GroupLayout.PREFERRED_SIZE, 1210, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ana_alan, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bilg_guncelle_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilg_guncelle_buttonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) p1_musteri_table.getModel();
        int selected_row_index = p1_musteri_table.getSelectedRow();

        if (selected_row_index != -1) {
            String musteri_id = model.getValueAt(selected_row_index, 0).toString();
            dialog_bilgi_doldur(musteri_id);
            musteri_guncelle.setLocationRelativeTo(null);
            musteri_guncelle.pack();
            musteri_guncelle.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Lütfen bir müşteri seçiniz!");
        }
    }//GEN-LAST:event_bilg_guncelle_buttonActionPerformed

    private void p2_kredi_reddet_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2_kredi_reddet_buttonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) p2_kredi_table.getModel();
        int selected_row_index = p2_kredi_table.getSelectedRow();

        if (selected_row_index != -1) {
            String selected_kredi_id = model.getValueAt(selected_row_index, 0).toString();
            this.b.krediRed(selected_kredi_id);
            p2_kredi_table_doldur();
            JOptionPane.showMessageDialog(null, "Red işlemi başarılı.");
        } else {
            JOptionPane.showMessageDialog(null, "Lütfen bir kredi işlemi seçiniz!");
        }
    }//GEN-LAST:event_p2_kredi_reddet_buttonActionPerformed

    private void p2_kredi_onayla_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2_kredi_onayla_buttonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) p2_kredi_table.getModel();
        int selected_row_index = p2_kredi_table.getSelectedRow();

        if (selected_row_index != -1) {
            String selected_kredi_id = model.getValueAt(selected_row_index, 0).toString();
            this.b.krediOnayla(selected_kredi_id);
            p2_kredi_table_doldur();
            JOptionPane.showMessageDialog(null, "Onay işlemi başarılı.");
        } else {
            JOptionPane.showMessageDialog(null, "Lütfen bir kredi işlemi seçiniz!");
        }

    }//GEN-LAST:event_p2_kredi_onayla_buttonActionPerformed

    private void mouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClicked
        // TODO add your handling code here:

        if (evt.getSource() == buton_panel_1) {
            p1.setVisible(true);
            p2.setVisible(false);
            p3.setVisible(false);
            p4.setVisible(false);
            p5.setVisible(false);
            p6.setVisible(false);
            p7.setVisible(false);
            p1_musteri_table_doldur();

        }

        if (evt.getSource() == buton_panel_2) {
            p1.setVisible(false);
            p2.setVisible(true);
            p3.setVisible(false);
            p4.setVisible(false);
            p5.setVisible(false);
            p6.setVisible(false);
            p7.setVisible(false);
            p2_kredi_table_doldur();
        }
        if (evt.getSource() == buton_panel_3) {
            p1.setVisible(false);
            p2.setVisible(false);
            p3.setVisible(true);
            p4.setVisible(false);
            p5.setVisible(false);
            p6.setVisible(false);
            p7.setVisible(false);
        }
        if (evt.getSource() == buton_panel_4) {
            p1.setVisible(false);
            p2.setVisible(false);
            p3.setVisible(false);
            p4.setVisible(true);
            p5.setVisible(false);
            p6.setVisible(false);
            p7.setVisible(false);
            p4_islem_table_doldur();
        }
        if (evt.getSource() == buton_panel_5) {
            p1.setVisible(false);
            p2.setVisible(false);
            p3.setVisible(false);
            p4.setVisible(false);
            p5.setVisible(true);
            p6.setVisible(false);
            p7.setVisible(false);
            p5_bilgi_doldur();
        }

        if (evt.getSource() == buton_panel_6) {
            p1.setVisible(false);
            p2.setVisible(false);
            p3.setVisible(false);
            p4.setVisible(false);
            p5.setVisible(false);
            p6.setVisible(true);
            p7.setVisible(false);
            p6_bilgi_doldur();
        }

        if (evt.getSource() == buton_panel_7) {
            p1.setVisible(false);
            p2.setVisible(false);
            p3.setVisible(false);
            p4.setVisible(false);
            p5.setVisible(false);
            p6.setVisible(false);
            p7.setVisible(true);
            p7_bilgi_doldur();
        }

    }//GEN-LAST:event_mouseClicked

    private void p3_ekle_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3_ekle_buttonActionPerformed
        // TODO add your handling code here:
        String ad = p3_ad.getText();
        String soyad = p3_soyad.getText();
        String sifre = p3_sifre.getText();
        String telefon = p3_telefon.getText();
        String tc = p3_tc.getText();
        String cinsiyet = p3_cinsiyet.getSelectedItem().toString();
        if (ad.equals("") || soyad.equals("") || sifre.equals("") || telefon.equals("") || tc.equals("") || cinsiyet.equals("")) {
            JOptionPane.showMessageDialog(null, "Yıldızlı alanlar boş bırakılamaz!");
        } else {
            this.b.musteriEkle(ad, soyad, sifre, telefon, tc, cinsiyet);
        }
    }//GEN-LAST:event_p3_ekle_buttonActionPerformed

    private void dialog_guncelle_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialog_guncelle_buttonActionPerformed

        DefaultTableModel model = (DefaultTableModel) p1_musteri_table.getModel();
        int selected_row_index = p1_musteri_table.getSelectedRow();
        String musteri_id = model.getValueAt(selected_row_index, 0).toString();
        String tc = model.getValueAt(selected_row_index, 4).toString();
        String cinsiyet = model.getValueAt(selected_row_index, 5).toString();
        if (dialog_ad.equals("") || dialog_soyad.equals("") || dialog_telefon.equals("") || dialog_sifre.equals("")) {
            JOptionPane.showMessageDialog(null, "Yıldızlı alanlar boş bırakılamaz!");
        } else {
            // TODO Auto-generated method stub
            this.b.musteriBilgiGuncelle(musteri_id, dialog_ad.getText(), dialog_soyad.getText(), dialog_sifre.getText(), dialog_telefon.getText(), tc, cinsiyet);
            JOptionPane.showMessageDialog(null, "Müşteri başarıyla güncellendi!");
            musteri_guncelle.setVisible(false);
            p1_musteri_table_doldur();
        }
    }//GEN-LAST:event_dialog_guncelle_buttonActionPerformed

    private void dialog_sifre_onay_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialog_sifre_onay_buttonActionPerformed
        // TODO add your handling code here:

        if (dialog_mevcut_sifre.getText().equals(this.b.password)) {
            if (!dialog_yeni_sifre.equals("")) {
                this.b.sifreDegistir(dialog_yeni_sifre.getText());
                sifre_degistir.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Şifre boş bırakılamaz!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Mevcut şifreyi yanlış girdiniz.");
        }
    }//GEN-LAST:event_dialog_sifre_onay_buttonActionPerformed

    private void p5_sifre_degistir_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p5_sifre_degistir_buttonActionPerformed
        // TODO add your handling code here:
        sifre_degistir.setLocationRelativeTo(null);
        sifre_degistir.pack();
        sifre_degistir.setVisible(true);
    }//GEN-LAST:event_p5_sifre_degistir_buttonActionPerformed

    private void musteri_guncelle_sil_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteri_guncelle_sil_buttonActionPerformed
        // TODO add your handling code here
        DefaultTableModel model = (DefaultTableModel) p1_musteri_table.getModel();
        int selected_row_index = p1_musteri_table.getSelectedRow();
        String musteri_id = model.getValueAt(selected_row_index, 0).toString();
        this.b.musteriSil(musteri_id);
        p1_musteri_table_doldur();
    }//GEN-LAST:event_musteri_guncelle_sil_buttonActionPerformed

    private void p3_adActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3_adActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p3_adActionPerformed

    private void p6_onay_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p6_onay_buttonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) p6_kredi_limit_table.getModel();
        int selected_row_index = p6_kredi_limit_table.getSelectedRow();

        String kredi_karti_id = model.getValueAt(selected_row_index, 0).toString();
        int yeni_limit = Integer.parseInt(model.getValueAt(selected_row_index, 2).toString());

        this.b.limitGuncelle(kredi_karti_id, yeni_limit);

        p6_bilgi_doldur();

    }//GEN-LAST:event_p6_onay_buttonActionPerformed

    private void p6_red_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p6_red_buttonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) p6_kredi_limit_table.getModel();
        int selected_row_index = p6_kredi_limit_table.getSelectedRow();

        String kredi_karti_id = model.getValueAt(selected_row_index, 0).toString();
        int yeni_limit = Integer.parseInt(model.getValueAt(selected_row_index, 2).toString());

        this.b.limitGuncelleme(kredi_karti_id, yeni_limit);

        p6_bilgi_doldur();
    }//GEN-LAST:event_p6_red_buttonActionPerformed

    private void p7_onayla_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p7_onayla_buttonActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) p7_kredi_table.getModel();
        int selected_row_index = p7_kredi_table.getSelectedRow();

        String kredi_karti_id = model.getValueAt(selected_row_index, 1).toString();
        this.b.krediKartiOnayla(kredi_karti_id);
        p7_bilgi_doldur();

    }//GEN-LAST:event_p7_onayla_buttonActionPerformed

    private void p7_red_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p7_red_buttonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) p7_kredi_table.getModel();
        int selected_row_index = p7_kredi_table.getSelectedRow();

        String kredi_karti_id = model.getValueAt(selected_row_index, 1).toString();
        this.b.krediKartiReddet(kredi_karti_id);
        p7_bilgi_doldur();
    }//GEN-LAST:event_p7_red_buttonActionPerformed

    public void p1_musteri_table_doldur() {
        DefaultTableModel model = (DefaultTableModel) p1_musteri_table.getModel();
        model.setRowCount(0);
        try {
            ArrayList<Object[]> o = this.b.musteriGetir();
            for (int i = 0; i < o.size(); i++) {
                model.addRow(o.get(i));
            }

        } catch (Exception ex) {
            Logger.getLogger(PersonelEkran.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void p2_kredi_table_doldur() {
        DefaultTableModel model = (DefaultTableModel) p2_kredi_table.getModel();
        model.setRowCount(0);
        try {
            ArrayList<Object[]> o = this.b.bekleyenKredileriGetir();
            for (int i = 0; i < o.size(); i++) {
                model.addRow(o.get(i));
            }

        } catch (Exception ex) {
            Logger.getLogger(PersonelEkran.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void p5_bilgi_doldur() {
        p5_calisan_id.setText(String.valueOf(this.b.id));
        p5_calisan_ad.setText(this.b.name);
        p5_calisan_soyad.setText(this.b.surname);
        p5_calisan_telefon.setText(this.b.telNumber);
        p5_calisan_tc.setText(this.b.tc);
        p5_calisan_unvan.setText(this.b.jobTitle);
        p5_calisan_maas.setText(String.valueOf(this.b.maas));
        p5_calisan_sube.setText(this.b.branch);
    }

    public void dialog_bilgi_doldur(String musteri_id) {
        try {
            // TODO Auto-generated method stub
            Scanner reader = new Scanner(new BufferedReader(new FileReader("musteri.txt")));
            while (reader.hasNextLine()) {
                String s = reader.nextLine();
                String[] bilgiler = s.split(",");
                if (bilgiler[0].equals(musteri_id)) {
                    dialog_ad.setText(bilgiler[1]);
                    dialog_soyad.setText(bilgiler[2]);
                    dialog_sifre.setText(bilgiler[3]);
                    dialog_telefon.setText(bilgiler[4]);
                }
            }
            reader.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Musteri.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void p4_islem_table_doldur() {
        DefaultTableModel model = (DefaultTableModel) p4_islem_table.getModel();
        model.setRowCount(0);
        try {
            ArrayList<Object[]> o = this.b.islemGecmisiGetir();
            for (int i = 0; i < o.size(); i++) {
                model.addRow(o.get(i));
            }

        } catch (Exception ex) {
            Logger.getLogger(PersonelEkran.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void p6_bilgi_doldur() {
        DefaultTableModel model = (DefaultTableModel) p6_kredi_limit_table.getModel();
        model.setRowCount(0);
        try {
            ArrayList<Object[]> o = this.b.limitIslemGetir();
            for (int i = 0; i < o.size(); i++) {
                model.addRow(o.get(i));
            }

        } catch (Exception ex) {
            Logger.getLogger(PersonelEkran.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void p7_bilgi_doldur() {
        DefaultTableModel model = (DefaultTableModel) p7_kredi_table.getModel();
        model.setRowCount(0);
        try {
            ArrayList<Object[]> o = this.b.krediKartiGetir();
            for (int i = 0; i < o.size(); i++) {
                model.addRow(o.get(i));
            }

        } catch (Exception ex) {
            Logger.getLogger(PersonelEkran.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonelEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonelEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonelEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonelEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonelEkran().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ana_alan;
    private javax.swing.JButton bilg_guncelle_button;
    private javax.swing.JPanel buton_panel_1;
    private javax.swing.JPanel buton_panel_2;
    private javax.swing.JPanel buton_panel_3;
    private javax.swing.JPanel buton_panel_4;
    private javax.swing.JPanel buton_panel_5;
    private javax.swing.JPanel buton_panel_6;
    private javax.swing.JPanel buton_panel_7;
    private javax.swing.JTextField dialog_ad;
    private javax.swing.JButton dialog_guncelle_button;
    private javax.swing.JPasswordField dialog_mevcut_sifre;
    private javax.swing.JPasswordField dialog_sifre;
    private javax.swing.JButton dialog_sifre_onay_button;
    private javax.swing.JTextField dialog_soyad;
    private javax.swing.JTextField dialog_telefon;
    private javax.swing.JPasswordField dialog_yeni_sifre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JDialog musteri_guncelle;
    private javax.swing.JButton musteri_guncelle_sil_button;
    private javax.swing.JPanel p1;
    private javax.swing.JTable p1_musteri_table;
    private javax.swing.JPanel p2;
    private javax.swing.JButton p2_kredi_onayla_button;
    private javax.swing.JButton p2_kredi_reddet_button;
    private javax.swing.JTable p2_kredi_table;
    private javax.swing.JPanel p3;
    private javax.swing.JTextField p3_ad;
    private javax.swing.JComboBox<String> p3_cinsiyet;
    private javax.swing.JButton p3_ekle_button;
    private javax.swing.JTextField p3_sifre;
    private javax.swing.JTextField p3_soyad;
    private javax.swing.JTextField p3_tc;
    private javax.swing.JTextField p3_telefon;
    private javax.swing.JPanel p4;
    private javax.swing.JTable p4_islem_table;
    private javax.swing.JPanel p5;
    private javax.swing.JTextField p5_calisan_ad;
    private javax.swing.JTextField p5_calisan_id;
    private javax.swing.JTextField p5_calisan_maas;
    private javax.swing.JTextField p5_calisan_soyad;
    private javax.swing.JTextField p5_calisan_sube;
    private javax.swing.JTextField p5_calisan_tc;
    private javax.swing.JTextField p5_calisan_telefon;
    private javax.swing.JTextField p5_calisan_unvan;
    private javax.swing.JButton p5_sifre_degistir_button;
    private javax.swing.JPanel p6;
    private javax.swing.JTable p6_kredi_limit_table;
    private javax.swing.JButton p6_onay_button;
    private javax.swing.JButton p6_red_button;
    private javax.swing.JPanel p7;
    private javax.swing.JTable p7_kredi_table;
    private javax.swing.JButton p7_onayla_button;
    private javax.swing.JButton p7_red_button;
    private javax.swing.JLabel personel_adi;
    private javax.swing.JDialog sifre_degistir;
    // End of variables declaration//GEN-END:variables
}
